services:
  postgres:
    image: postgres:16.3
    container_name: matrix_postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: synapse
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: synapse
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C --lc-collate=C --lc-ctype=C"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - matrix

  synapse:
    image: matrixdotorg/synapse:v1.130.0
    container_name: matrix_synapse
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      SYNAPSE_SERVER_NAME: synapse-chat.insomniafest.ru
      SYNAPSE_REPORT_STATS: "no"
      SYNAPSE_REGISTRATION_SHARED_SECRET: ${SYNAPSE_REGISTRATION_SHARED_SECRET}
      MACAROON_SECRET_KEY: ${MACAROON_SECRET_KEY}
      FORM_SECRET: ${FORM_SECRET}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./config/synapse:/data
    entrypoint: ["/bin/sh", "/data/start.sh"]
    networks:
      - matrix
    expose:
      - "8008"

  element-web:
    image: vectorim/element-web:v1.12.6
    container_name: matrix_element
    restart: unless-stopped
    depends_on:
      - synapse
    networks:
      - matrix
    expose:
      - "80"
    volumes:
      - ./config/element/config.json:/app/config.json:ro
      - ./config/element/assets:/app/assets:ro

  nginx-front:
    image: nginx:alpine
    container_name: matrix_nginx
    restart: unless-stopped
    depends_on:
      - element-web
      - synapse
    networks:
      - matrix
    ports:
      - "127.0.0.1:18080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/html:/usr/share/nginx/html:ro

  livekit:
    image: livekit/livekit-server:latest
    container_name: matrix_livekit
    restart: unless-stopped
    command: --config /etc/livekit.yaml
    volumes:
      - ./config/livekit/livekit.yaml:/etc/livekit.yaml:ro
    networks:
      - matrix
    expose:
      - "7880"
      - "7881"
    ports:
      - "50000-50100:50000-50100/udp"


networks:
  matrix:
    driver: bridge
